import { google } from 'googleapis';

export const dynamic = 'force-dynamic';

export async function GET() {
  try {
    const clientId = process.env.GMAIL_CLIENT_ID;
    const clientSecret = process.env.GMAIL_CLIENT_SECRET;
    const refreshToken = process.env.GMAIL_REFRESH_TOKEN;
    const gmailUser = process.env.GMAIL_USER;
    const supabaseUrl = process.env.SUPABASE_URL;
    const serviceKey = process.env.SUPABASE_SERVICE_KEY;

    if (!clientId ||!clientSecret ||!refreshToken ||!gmailUser) {
      return Response.json({ success: false, fetched: 0, inserted: 0, lastErr: 'Missing GMAIL_ env vars', envOk: false }, { status: 500 });
    }

    const oauth2Client = new google.auth.OAuth2(clientId, clientSecret);
    oauth2Client.setCredentials({ refresh_token: refreshToken });
    const gmail = google.gmail({ version: 'v1', auth: oauth2Client });

    const { createClient } = await import('@supabase/supabase-js');
    const supabase = createClient(supabaseUrl!, serviceKey!);

    const { data: jobs } = await supabase.from('jobs').select('*').eq('tailored', true).eq('draft_created', false).limit(5);

    let inserted = 0;
    let lastErr = '';
    const fetched = jobs?.length || 0;

    for (const job of jobs || []) {
      try {
        const subject = `Founding Full-Stack AI Engineer — Imran Afzal — 8-agent engine live 50 cities — EST overlap — ${job.company}`;
        const to = job.contact_email || job.email || 'hiring@' + (job.company?.toLowerCase().replace(/\s+/g,'') || 'company') + '.com';

        const body = `
          <div style="font-family:Inter,sans-serif;max-width:600px;line-height:1.6">
            <p>Hi ${job.company} team,</p>
            <p>${job.cover_letter || job.tailored_summary}</p>

            <p><b>Live proof (not just resume):</b><br/>
            - Engine: <a href="https://github.com/venusplaza7-dot/venus-ai-v7">venus-ai-v7</a> (8 agents, 100/day/city)<br/>
            - Live demo: <a href="https://venus-ai-v8.vercel.app/toyota-of-denver?niche=auto">AI receptionist booking on WhatsApp</a><br/>
            - Portfolio: All 15 repos + case studies</p>

            <p><b>Why I fit ${job.title}:</b><br/>
            Matched: ${(job.matched_keywords||[]).join(', ')} | Remote full-time with 4h EST overlap | BCC-proofed delivery (Venus OS)</p>

            <p>Open to quick 15-min call?<br/>
            📧 Venusplaza7@gmail.com<br/>
            📞 +92 321 797 3545 | <a href="https://wa.me/923217973545">WhatsApp</a><br/>
            💻 github.com/venusplaza7-dot</p>

            <p style="color:#666;font-size:12px">This draft was auto-generated by job-agents-real — BCC: venusailux@gmail.com for audit</p>
          </div>
        `;

        const rawMessage = [
          `From: ${gmailUser}`,
          `To: ${to}`,
          `Bcc: venusailux@gmail.com`,
          `Subject: ${subject}`,
          `Content-Type: text/html; charset=utf-8`,
          `MIME-Version: 1.0`,
          ``,
          `${body}`,
        ].join('\n');

        const encoded = Buffer.from(rawMessage)
         .toString('base64')
         .replace(/\+/g, '-')
         .replace(/\//g, '_')
         .replace(/=+$/, '');

        await gmail.users.drafts.create({
          userId: 'me',
          requestBody: { message: { raw: encoded } },
        });

        await supabase.from('jobs').update({ draft_created: true }).eq('id', job.id);
        inserted++;
      } catch (e: any) {
        lastErr = e.message;
        console.error(e);
      }
    }

    return Response.json({ success: true, fetched, inserted, lastErr, envOk: true });
  } catch (e: any) {
    return Response.json({ success: false, fetched: 0, inserted: 0, lastErr: e.message, envOk: true }, { status: 500 });
  }
}
