export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';
const GROQ_API_KEY = "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";
const SUPABASE_URL = "https://ekubsfgyuqziizfjmcs-k.supabase.co";
const SUPABASE_KEY = "sb_publishable_kHr0-nudVWjliHw_owPm7A_G1NA4i8o";
const BREVO_API_KEY = "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";
const SENDER_EMAIL = "ron@venushq7.com";
const BCC_EMAIL = "venusailux@gmail.com";
export async function GET(){try{const{createClient}=await import('@supabase/supabase-js');const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);const r=await fetch("https://remoteok.com/api?tag=ai",{headers:{"User-Agent":"Mozilla/5.0"}});const data=await r.json();const jobs=data.slice(1,8).map(j=>({title:j.position,company:j.company,location:j.location||"Remote",url:j.url,description:(j.description||"").slice(0,2000)}));let new_saved=0;let emails_sent=0;for(const job of jobs){const groq=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Authorization":`Bearer ${GROQ_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:"openai/gpt-oss-20b",messages:[{role:"system",content:"You are a senior resume writer. Return JSON with tailored_resume, cover_letter, match_score."},{role:"user",content:`JOB: ${job.title} at ${job.company}. DESC: ${job.description}. Return JSON.`}],response_format:{type:"json_object"}})});const gj=await groq.json();let ai={};try{ai=JSON.parse(gj.choices?.[0]?.message?.content||"{}")}catch{}await supabase.from('jobs').insert({title:job.title,company:job.company,location:job.location,url:job.url,description:job.description,tailored_resume:ai.tailored_resume||"",cover_letter:ai.cover_letter||"",match_score:ai.match_score||0,created_at:new Date().toISOString()});new_saved++;await fetch("https://api.brevo.com/v3/smtp/email",{method:"POST",headers:{"api-key":BREVO_API_KEY,"Content-Type":"application/json"},body:JSON.stringify({sender:{name:"Imran Afzal",email:SENDER_EMAIL},to:[{email:BCC_EMAIL}],bcc:[{email:BCC_EMAIL}],subject:`Application: ${job.title} at ${job.company}`,htmlContent:`<p>Hi ${job.company}</p><p>${job.title} - ${job.location}</p><p>${ai.cover_letter||""}</p><p>Resume: https://job-agents-real.vercel.app/resume.pdf</p><pre>${ai.tailored_resume||""}</pre>`})});emails_sent++;}return new Response(JSON.stringify({ok:true,scraped:jobs.length,new_saved,emails_sent,groq_works:true,time:new Date().toISOString()}),{headers:{"Content-Type":"application/json"}})}catch(err){return new Response(JSON.stringify({ok:false,error:err.message}),{status:500})}}
